import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "NextJS Testing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  dashboard,
}: Readonly<{
  children: React.ReactNode;
  dashboard: React.ReactNode;
}>) {
  const isAdmin = false;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-between md:w-4/5 mx-auto items-center px-3 md:px-14 py-2 md:rounded-b bg-blue-600 text-white">
          <Link href={"/"}>
            <h2 className="font-bold text-3xl uppercase">bloggy</h2>
          </Link>
          <Link
            href={"/create"}
            className="p-2 text-blue-700 bg-white rounded font-semibold text-sm hover:bg-gray-100 active:scale-95 duration-200"
          >
            Create new blog
          </Link>
        </nav>
        <div className="px-3 w-4/5 md:w-3/5 mx-auto">{children}</div>
        {isAdmin && dashboard}
      </body>
    </html>
  );
}
